#!/usr/bin/env python3
"""simulate_team — generate 4 synthetic personas + extract signatures for all 5 team members.

Produces a "team-of-5" for demo Beat 2: 4 synthetic personas + the user's real signature.
Each persona gets ~30 fake directives generated by Opus in-voice, ingested, and extracted
into its own signature.<name>.json. Output: signature-grid.md comparing all 5 side-by-side.

Usage:
    export ANTHROPIC_API_KEY=sk-ant-...
    python3 measurement/simulate_team.py [--repo PATH] [--model claude-opus-4-7]
                                          [--directives-per-persona N] [--user-signature PATH]
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path


MODEL_DEFAULT = "claude-opus-4-7"


PERSONAS = {
    "terse": {
        "label": "Alice — terse engineer",
        "voice": "Terse engineer. Ships-it culture. Minimal words. Uses 'lgtm', 'ship it', 'wdyt', 'nope', 'yep'. Arrows (->) common. Technical shorthand. Heavy lowercase. No fluff. Pushes back with 'nah'.",
    },
    "verbose": {
        "label": "Bob — verbose PM",
        "voice": "Verbose project manager. Consensus-building. Asks many questions. 'Could we consider', 'I'd love to get input on', 'thoughts?', 'circling back'. Long sentences. Proper punctuation. Uses 'team' often. Thanks people.",
    },
    "casual": {
        "label": "Tim — casual lowercase",
        "voice": "Casual lowercase typer. No capitalization. Stream of consciousness. 'fwiw', 'idk but', 'lmao', 'tbh', 'tldr', 'ngl'. Missing apostrophes. Extra letters for emphasis ('sooo'). Sprinkles 'like' and 'ya know'.",
    },
    "formal": {
        "label": "Sue — formal academic",
        "voice": "Formal academic register. 'Pursuant to', 'furthermore', 'I posit', 'it behooves us'. Full sentences. Semicolons common. Proper grammar. Structured arguments. Cites authorities. Never casual.",
    },
}


GENERATE_PROMPT = """Generate {n} realistic chat messages that a user would type TO an AI assistant, in this specific voice:

{voice}

Each message should be a real directive/question/hunch the user might type during a work session — things like asking for help with a task, pushing back on an AI's suggestion, making a hunch-statement, requesting changes, or expressing a trust signal. Vary the topics (code, docs, planning, debugging, discussions) but keep the VOICE consistent across all {n} messages.

Output ONLY a JSON array of strings. No preamble, no numbering, no markdown. Just:
["message 1", "message 2", ...]

Each message 30-250 characters. Total {n} messages."""


def generate_persona_directives(client, model: str, voice: str, n: int = 30) -> list[str]:
    prompt = GENERATE_PROMPT.format(n=n, voice=voice)
    response = client.messages.create(
        model=model,
        max_tokens=4096,
        messages=[{"role": "user", "content": prompt}],
    )
    text = "".join(block.text for block in response.content if getattr(block, "type", None) == "text").strip()
    if text.startswith("```"):
        text = text.split("```", 2)[1]
        if text.startswith("json"):
            text = text[4:]
        text = text.strip().rstrip("`").strip()
    return json.loads(text)


def write_persona_jsonl(directives: list[str], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        for i, directive in enumerate(directives):
            row = {
                "ts": datetime.now(timezone.utc).isoformat(),
                "type": "user",
                "content": directive,
                "source": "user",
                "synthetic": True,
                "index": i,
            }
            f.write(json.dumps(row) + "\n")


def run_cmd(cmd: list[str]) -> int:
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        print(result.stdout, file=sys.stderr)
        print(result.stderr, file=sys.stderr)
    return result.returncode


def extract_signature_for_persona(repo: Path, persona_id: str, corpus_path: Path, model: str) -> Path:
    ingest_script = repo / "skills" / "capture" / "dialogue_ingest.py"
    extract_script = repo / "skills" / "extract" / "extract.py"

    run_cmd([
        sys.executable, str(ingest_script),
        "--repo", str(repo),
        "--input", str(corpus_path),
        "--source-filter", "user",
        "--min-chars", "20",
        "--max-samples", "30",
        "--scope-name", persona_id,
    ])
    run_cmd([
        sys.executable, str(extract_script),
        "--repo", str(repo),
        "--domain", "directing",
        "--scope-name", persona_id,
        "--model", model,
        "--advisor", "off",
    ])
    return repo / f"signature.{persona_id}.json"


def render_grid(signatures: list[tuple[str, str, dict]], out_path: Path) -> None:
    """signatures: list of (persona_id, label, signature_dict)"""
    lines = [
        "# Cogsig Team Simulation — 5-Person Signature Grid",
        "",
        f"Generated {datetime.now(timezone.utc).isoformat()}",
        "",
        "Five team members. Four synthetic personas + one real user. Same pipeline, distinct signatures across all 7 dimensions. Architecture visibly differentiates voices.",
        "",
    ]
    for persona_id, label, sig in signatures:
        dims = sig.get("dimensions", {})
        lines.append(f"## {label}")
        lines.append("")
        origin = sig.get("origin", "?")
        sample_count = sig.get("sample_count", "?")
        synthetic_tag = " (synthetic)" if persona_id != "flex" else " (real)"
        lines.append(f"- **origin**: {origin}{synthetic_tag} | **samples**: {sample_count}")

        name = dims.get("idiomatic_tells", {})
        if isinstance(name, dict):
            opens = name.get("openings", [])
            vocab = name.get("vocabulary_signature", [])
            caps = name.get("capitalization_style", "?")
            if vocab:
                lines.append(f"- **vocabulary**: {', '.join(str(v) for v in vocab[:6])}")
            if opens:
                lines.append(f"- **openings**: {', '.join(str(o) for o in opens[:4])}")
            lines.append(f"- **caps**: {caps}")

        dstyle = dims.get("directive_style", {})
        if isinstance(dstyle, dict):
            mode = dstyle.get("primary_mode", "?")
            terse = dstyle.get("terse_vs_verbose", "?")
            lines.append(f"- **directive style**: {mode} | {terse}")

        cr = dims.get("compression_ratio", {})
        if isinstance(cr, dict):
            avg = cr.get("avg_directive_chars", "?")
            pref = cr.get("preference", "?")
            lines.append(f"- **compression**: avg {avg} chars | {pref}")

        te = dims.get("texture_energy", {})
        if isinstance(te, dict):
            baseline = te.get("baseline_energy", "?")
            high = te.get("high_energy_markers", [])
            lines.append(f"- **energy**: {baseline} | high-markers: {', '.join(str(h) for h in high[:4])}")

        rp = dims.get("reframe_pattern", {})
        if isinstance(rp, dict):
            freq = rp.get("frequency", "?")
            style = rp.get("style", "?")
            lines.append(f"- **reframe**: {freq} | {style}")

        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Simulate a 5-person team: 4 synthetic personas + user.")
    ap.add_argument("--repo", type=Path, default=Path.cwd())
    ap.add_argument("--model", default=MODEL_DEFAULT)
    ap.add_argument("--directives-per-persona", type=int, default=30)
    ap.add_argument("--user-signature", type=Path, default=None,
                    help="Path to the real user's existing signature (default: signature.alice.json)")
    ap.add_argument("--out", type=Path, default=None, help="Grid output path (default: measurement/signature-grid.md)")
    args = ap.parse_args()

    try:
        import anthropic
    except ImportError:
        print("error: anthropic SDK not installed", file=sys.stderr)
        return 1

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("error: ANTHROPIC_API_KEY not set", file=sys.stderr)
        return 2

    repo = args.repo.resolve()
    client = anthropic.Anthropic(api_key=api_key)

    user_sig_path = args.user_signature or (repo / "signature.alice.json")
    out_path = args.out or (repo / "measurement" / "signature-grid.md")

    collected: list[tuple[str, str, dict]] = []

    # 1. Generate + extract 4 synthetic personas
    for persona_id, spec in PERSONAS.items():
        print(f"\n=== persona: {persona_id} — {spec['label']} ===", file=sys.stderr)
        print(f"[1/3] generating {args.directives_per_persona} directives...", file=sys.stderr)
        directives = generate_persona_directives(client, args.model, spec["voice"], n=args.directives_per_persona)
        print(f"  generated {len(directives)} directives", file=sys.stderr)

        with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False, encoding="utf-8") as tf:
            corpus_path = Path(tf.name)
        try:
            write_persona_jsonl(directives, corpus_path)
            print(f"[2/3] ingest + extract signature for '{persona_id}'...", file=sys.stderr)
            sig_path = extract_signature_for_persona(repo, persona_id, corpus_path, args.model)
            if not sig_path.exists():
                print(f"  WARN: signature not written for {persona_id}", file=sys.stderr)
                continue
            sig = json.loads(sig_path.read_text(encoding="utf-8"))
            collected.append((persona_id, spec["label"], sig))
            print(f"[3/3] done: {sig_path}", file=sys.stderr)
        finally:
            try:
                corpus_path.unlink()
            except OSError:
                pass

    # 2. Add user's real signature as 5th team member
    if user_sig_path.exists():
        user_sig = json.loads(user_sig_path.read_text(encoding="utf-8"))
        collected.append(("flex", "Flex — real user (cc history extracted)", user_sig))
        print(f"\n[5/5] user signature added from {user_sig_path}", file=sys.stderr)
    else:
        print(f"\nwarn: user signature not found at {user_sig_path} — grid will have 4 personas only", file=sys.stderr)

    render_grid(collected, out_path)
    print(f"\nwrote {out_path}")
    print(f"  {len(collected)} signatures in grid")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
